### ISSUE TITLE
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed

### ISSUE THREAD

**Issue by razbakov** [EliasKotlyar/Twinsen_DeployHelper#2]
### Steps to reproduce

I followed installation instructions in readme and ran:

   composer require twinsen/deployhelper
   bin/magento module:enable Twinsen_DeployHelper
   bin/magento setup:upgrade
   bin/magento deployhelper:generatedb
### Actual result

I've got this message:

```
[Zend_Db_Adapter_Exception]
The sqlite driver is not currently installed
```
### Expected result

Generated sqlite database

**Comment by EliasKotlyar** [comment]
Hello @razbakov ,

Try:
```
apt-get install php-sqlite
```

That should resolve the issue.

Greatings
Elias
